services:
  - type: web
    name: currency-converter
    env: java
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/currency_converter-0.0.1-SNAPSHOT.jar"
    plan: starter
    envVars:
      - key: RAPIDAPI_KEY
        sync: false
      - key: RAPIDAPI_HOST
        sync: false
      - key: CURRENCY_API_SYMBOLS_URL
        sync: false
      - key: CURRENCY_API_CONVERT_URL
        sync: false
